"""
Automated engineering report generator.

Creates comprehensive markdown compliance reports summarizing thermodynamic, 
mechanical, control, and environmental outcomes of AWR reactor runs.
"""

from typing import Dict, Any, List

class ComplianceReportGenerator:
    """
    Formulates and writes official, professional-grade engineering and safety reports
    summarizing reactor runs, ASME structural calculations, and ISO compliance.
    """
    
    def __init__(self):
        pass
        
    def generate_markdown_report(
        self,
        sim_summary: Dict[str, float],
        asme_results: Dict[str, float],
        iso_results: Dict[str, Any],
        efficiency_results: Dict[str, float],
        co2_results: Dict[str, float]
    ) -> str:
        """
        Synthesize run telemetry and design calculations into a beautiful engineering report.
        """
        
        report = []
        report.append("# ASRHÜR REACTON ENGINEERING COMPLIANCE REPORT")
        report.append("---")
        report.append("## ⚡ SYSTEM SUMMARY & PERFORMANCE")
        report.append("| Parameter | Value | Status |")
        report.append("|-----------|-------|--------|")
        report.append(f"| **Active Conversion fraction ($\\alpha$)** | {sim_summary['final_conversion_fraction']:.2%} | {'✅ Complete' if sim_summary['final_conversion_fraction'] >= 0.95 else '⚠️ Incomplete'} |")
        report.append(f"| **Max Reaction Temperature** | {sim_summary['max_temperature_c']:.2f} °C | { '✅ Safe (<95°C)' if sim_summary['max_temperature_c'] < 95.0 else '🚨 Runaway Danger' } |")
        report.append(f"| **Max Reactor Pressure** | {sim_summary['max_pressure_bar']:.2f} bar | { '✅ Under Design' if sim_summary['max_pressure_bar'] < 16.0 else '🚨 High Pressure' } |")
        report.append(f"| **Total Hydrogen Produced** | {sim_summary['total_hydrogen_produced_g']:.2f} g | ✅ Yield Logged |")
        
        report.append("\n## 🔬 THERMODYNAMIC & SYSTEM EFFICIENCY")
        report.append(f"- **Lower Heating Value (LHV) Efficiency:** {efficiency_results['lhv_system_efficiency']:.2%}")
        report.append(f"- **Higher Heating Value (HHV) Efficiency:** {efficiency_results['hhv_system_efficiency']:.2%}")
        report.append(f"- **Second-Law Exergy Efficiency:** {efficiency_results['second_law_exergy_efficiency']:.2%}")
        report.append(f"- **Volumetric Hydrogen Capacity:** {efficiency_results['volumetric_capacity_g_h2_l']:.2f} g-H₂/L-reactants")
        report.append(f"- **Gravimetric Feedstock Capacity:** {efficiency_results['gravimetric_feedstock_capacity_wt']:.2f} wt%")
        report.append(f"- **Gravimetric Total System Capacity:** {efficiency_results['gravimetric_system_capacity_wt']:.2f} wt%")
        
        report.append("\n## 🛠️ ASME SECTION VIII MECHANICAL DESIGN COMPLIANCE")
        report.append(f"- **Vessel Inside Diameter:** {asme_results['vessel_inside_diameter_mm']:.1f} mm")
        report.append(f"- **Material Allowable Stress (S):** {asme_results['allowable_stress_psi']:.1f} PSI")
        report.append(f"- **Required Cylindrical Shell Wall Thickness ($t_s$):** **{asme_results['calculated_shell_thickness_mm']:.3f} mm**")
        report.append(f"- **Required 2:1 Ellipsoidal Head Wall Thickness ($t_h$):** **{asme_results['calculated_head_thickness_mm']:.3f} mm**")
        
        report.append("\n## 🛡️ ISO 16110 SAFETY SCORECARD")
        compliance_icon = "✅ COMPLIANT" if iso_results["iso_16110_compliant"] else "❌ NON-COMPLIANT"
        report.append(f"### Status: **{compliance_icon}**")
        report.append(f"**Standard Reference:** *{iso_results['standard_reference']}*")
        
        if len(iso_results["active_violations"]) > 0:
            report.append("\n**Active Safety Standard Violations:**")
            for violation in iso_results["active_violations"]:
                report.append(f"- 🔴 `{violation}`")
        else:
            report.append("\n- 🟢 No active ISO 16110 safety violations detected. System meets all design guidelines.")
            
        report.append("\n## 🌱 DECARBONIZATION FOOTPRINT (CO₂ OFFSETS)")
        report.append("By generating high-purity hydrogen on-demand utilizing recycled/premium aluminum feedstock instead of fossil energy supplies, this run achieved:")
        report.append(f"- **Carbon Saved vs. Steam Methane Reforming (SMR):** **{co2_results['co2_saved_vs_smr_kg']:.3f} kg CO₂**")
        report.append(f"- **Carbon Saved vs. Coal Grid Electrolysis:** **{co2_results['co2_saved_vs_coal_grid_kg']:.3f} kg CO₂**")
        
        report.append("\n---")
        report.append("**Report Generated by:** ReactoN Automated Engineering Engine  ")
        report.append("**Owner:** ASRHÜR Kimya ve Makina Sanayi A.Ş.  ")
        report.append("**TRL Class:** TRL 5 (System Prototype Validation in Operational Environment)")
        
        return "\n".join(report)
